export { default as Dashboard } from './Dashboard';
export { default as NotFound } from './NotFound';
export { default as AuthPhonePage, MobileAuthPhonePage } from './AuthPhonePage';
export { default as AuthCodePage, MobileAuthCodePage } from './AuthCodePage';
export { ServicesPage } from './ServicesPage';
export { default as MobileServicesPage } from './ServicesPage/MobileServicesPage';
export { OrdersPage, MobileOrdersPage } from './OrdersPage';
export { AnalyticsPage, MobileAnalyticsPage } from './AnalyticsPage';
export { SchedulePage, MobileSchedulePage } from './SchedulePage';
export { PaymentMockPage } from './PaymentMockPage';
export { default as SettingsPage } from './SettingsPage';
export { MobileNotificationsPage } from './NotificationsPage/MobileNotificationsPage';
